#::::::::::::::-------------------------------------...-----------------------------::::::::::::::::
#:::::::::::::----------------------------------......----------------------------------::::::::::::
#:::::::::::------------------------------...............-----------------------------------::::::::
#::::::::::-----------------------------.------........``..------------------------------------:::::
#:::::::::--------------------------.............`..`````..........------------------------------:::
#:::::---------------------------...```........`````-yo``````..........---------------------------::
#::::::--::---------------------..````....``````` +yhNh ```````.........--------------------------::
#::::::--:--------------------..```  `````        yNh/:    `````..........----------------------::::
#:::::::----------------------.`      `````   +ooodNdo+    `````...........---------------------::::
#------------------------------.`    ` ``-ssssoodmmmdssssss. ``..``.........-........------------:::
#:-----------...................`      -+ossss--+osyo:/yyyyo+-```````.............`.........--------
#:-------.......````````````````     ` /Nh..````.--::.-:://dN:```````````````````````...............
#------......```````````````````     `/+os+``  ``........-//syo+:    ````     ```````...............
#---..................`````          `yNy..    ..........-////dNs           ````..........```.......
#......................```          ``yNy..````..........-////dNs        ```.............`````......
#........--..........````   ```     ``yNy..............---////dNs   `  `````....```..```````........
#.......--........````````````````````ohs/:--........--:////ooyho```````````````````````............
#-------............``........``````````/Nd//--------:+/////dN/.`````````..``````.......------------
#------------.......---------....``..../mh++////+++++////++hm:.....``.........----------------------
#-----------------------------...........:dh++++hdddy++++dm-.....``.........------------------------
#------------------------------...-........-mmmd:```:mddd-``````````.......---------------------::::
#:-----------------------------.--..........``````````````````..````.....------------------------:::
#::::------------------------------........................``...``.......-------------------::::::::
#:::::::::-------------------------...................`.......````..`..------------------------:::::
#:::::::::--------------------------.................................-.-------------------------::::
#Thanks to http://www.text-image.com/convert/pic2ascii.cgi, for the image to ascii


store:
  type: 'file'
  #<-- NOT COMPLETE YET-->
  #type: 'sql'
  #host: '172.0.0.1:3306'
  #user: 'root'
  #password: 'password'
  #databse: 'public-uhc'

settings:
  spawn:
    world: 'world'
    x: 0
    y: 64
    z: 0