name: PublicUHC
version: ${project.version}
main: com.itserikmc.open.publicuhc.PublicUHC
authors: [ItsErikMC]
description: An open-source simple UHC system.
website: https://github.com/ItsErikMC/public-uhc/
